import streamlit as st
import speech_recognition as sr
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
import time
import os
from io import BytesIO
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

# Page Configuration
st.set_page_config(
    page_title="AI Meeting Assistant & Executive Reporter",
    page_icon="🚀",
    layout="centered"
)

st.title("🚀 Enterprise AI Meeting Assistant")
st.write("Advanced speech transcription featuring **AI action item extraction**, and **PDF report generation**.")

# Initialize Session State
if "transcript" not in st.session_state:
    st.session_state.transcript = ""
if "summary" not in st.session_state:
    st.session_state.summary = ""
if "actions" not in st.session_state:
    st.session_state.actions = []

# Tabs for input choices
tab1, tab2 = st.tabs(["🎙️ Live Browser Recording", "📁 Upload WAV Audio File"])

audio_file = None

with tab1:
    st.info("Record your meeting discussion directly using your browser microphone.")
    live_audio = st.audio_input("Record audio stream", key="live_recorder")
    
with tab2:
    uploaded_file = st.file_uploader("Upload a meeting WAV file", type=["wav"], key="file_uploader")

# Intelligent selection: use live recording if available, otherwise check file uploader
if live_audio is not None:
    audio_file = live_audio
elif uploaded_file is not None:
    audio_file = uploaded_file

def extract_action_items(text):
    """Rule-based NLP keyword extraction for meeting tasks and deliverables"""
    sentences = text.split('.')
    action_keywords = ["todo", "action", "need to", "will", "assign", "complete", "by tomorrow", "next week", "deadline", "ensure"]
    found_actions = []
    for sentence in sentences:
        if any(keyword in sentence.lower() for keyword in action_keywords):
            cleaned = sentence.strip()
            if len(cleaned) > 5:
                found_actions.append(cleaned)
    return found_actions

def generate_pdf_report(transcript, summary, actions):
    """Generates a professional PDF document stream using ReportLab"""
    pdf_buffer = BytesIO()
    doc = SimpleDocTemplate(pdf_buffer, pagesize=letter, rightMargin=36, leftMargin=36, topMargin=36, bottomMargin=36)
    story = []
    
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle('DocTitle', parent=styles['Heading1'], fontSize=18, textColor='#1f4e78', spaceAfter=12)
    heading_style = ParagraphStyle('SectionHeading', parent=styles['Heading2'], fontSize=14, textColor='#2c3e50', spaceBefore=12, spaceAfter=6)
    body_style = ParagraphStyle('BodyTextCustom', parent=styles['Normal'], fontSize=10, textColor='#333333', spaceAfter=8, leading=14)
    
    story.append(Paragraph("Executive Meeting Intelligence Report", title_style))
    story.append(Paragraph("<b>Generated by AI Meeting Assistant</b>", body_style))
    story.append(Spacer(1, 10))
    
    story.append(Paragraph("1. Executive Summary", heading_style))
    story.append(Paragraph(summary if summary else "No summary available.", body_style))
    story.append(Spacer(1, 10))
    
    story.append(Paragraph("2. Tracked Action Items & Responsibilities", heading_style))
    if actions:
        for idx, act in enumerate(actions, 1):
            story.append(Paragraph(f"• <b>Task {idx}:</b> {act}.", body_style))
    else:
        story.append(Paragraph("No explicit action items found.", body_style))
    story.append(Spacer(1, 10))
    
    story.append(Paragraph("3. Full Transcript", heading_style))
    story.append(Paragraph(transcript if transcript else "No transcript available.", body_style))
    
    doc.build(story)
    pdf_buffer.seek(0)
    return pdf_buffer

if audio_file is not None:
    st.audio(audio_file)
    
    if st.button("⚙️ Process & Analyze Audio", type="primary"):
        unique_filename = f"audio_{int(time.time())}.wav"
        
        with open(unique_filename, "wb") as f:
            f.write(audio_file.getbuffer())
            
        with st.status("🛠️ Running Audio Pipeline & Neural Analysis...", expanded=True) as status:
            try:
                st.write("1️⃣ Loading current audio stream...")
                
                st.write("2️⃣ Converting clean speech stream to text (Google API)...")
                recognizer = sr.Recognizer()
                with sr.AudioFile(unique_filename) as source:
                    audio_data = recognizer.record(source)
                    text = recognizer.recognize_google(audio_data)
                    st.session_state.transcript = text
                
                st.write("3️⃣ Summarizing with Hugging Face BART Transformer...")
                model_id = "sshleifer/distilbart-cnn-12-6"
                tokenizer = AutoTokenizer.from_pretrained(model_id)
                model = AutoModelForSeq2SeqLM.from_pretrained(model_id)
                
                inputs = tokenizer(text, return_tensors="pt", max_length=1024, truncation=True)
                summary_ids = model.generate(**inputs, max_length=130, min_length=15, do_sample=False)
                summary = tokenizer.decode(summary_ids[0], skip_special_tokens=True)
                st.session_state.summary = summary
                
                st.write("4️⃣ Scanning text patterns for action items...")
                st.session_state.actions = extract_action_items(text)
                
                status.update(label="✅ Processing Complete Successfully!", state="complete", expanded=False)
                
            except sr.UnknownValueError:
                st.error("❌ Google Speech Recognition could not understand the speech in this audio. Please speak louder or use a clearer recording.")
            except sr.RequestError as e:
                st.error(f"⚠️ Network Error connecting to Google API: {e}")
            except Exception as e:
                import traceback
                st.error(f"Pipeline Execution Error: {e}")
                st.code(traceback.format_exc(), language="python")
            finally:
                if os.path.exists(unique_filename):
                    os.remove(unique_filename)

# Display Results Dashboard
if st.session_state.transcript:
    st.divider()
    
    col1, col2 = st.columns(2)
    with col1:
        st.subheader("📝 Full Transcript")
        st.text_area("Transcript Output", st.session_state.transcript, height=220, disabled=True)
    with col2:
        st.subheader("📊 Executive Summary")
        st.text_area("Summary Output", st.session_state.summary, height=220, disabled=True)
        
    st.subheader("📌 Extracted Action Items")
    if st.session_state.actions:
        for idx, action in enumerate(st.session_state.actions, 1):
            st.markdown(f"- **Task {idx}:** {action}")
    else:
        st.info("No explicit action items or assigned deadlines identified.")
        
    st.divider()
    st.subheader("📥 Export Enterprise Report")
    
    pdf_data = generate_pdf_report(st.session_state.transcript, st.session_state.summary, st.session_state.actions)
    
    st.download_button(
        label="📄 Download Official PDF Report",
        data=pdf_data,
        file_name="Executive_Meeting_Report.pdf",
        mime="application/pdf"
    )